/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.virginia.cs.model;

import edu.virginia.cs.utility.FileOperations;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Wasi
 */
public class GenerateTopicWords {

    /**
     * Method that stores topical word distribution for each topic.
     *
     * @param betaFile file generated by LDA-C
     * @param dictFile dictionary file
     * @throws java.Throwable
     */
    private void storeTopicWordDistribution(String betaFile, String dictFile) throws Throwable {
        String filepath = "topic_repo/topic ";
        FileOperations fiop = new FileOperations();
        ArrayList<String> vocab = fiop.LoadFile(dictFile, -1);
        ArrayList<String> lines = fiop.LoadFile(betaFile, -1);
        HashMap<String, Double> unsortedMap = new HashMap<>();
        int x = 0;
        for (String line : lines) {
            String values[] = line.split(" ");
            Double total = 0.0;
            for (int i = 0; i < values.length; i++) {
                Double d = Math.pow(Math.E, Double.valueOf(values[i]));
                unsortedMap.put(vocab.get(i), d);
                total = total + d;
            }
            System.out.println(total);
            sortByComparator(unsortedMap, false, filepath + String.valueOf(x) + ".txt");
            x++;
        }
    }

    /**
     * Method that generate the id of all users for evaluation.
     *
     * @param unsortMap unsorted Map
     * @param order if true, then sort in ascending order, otherwise in
     * descending order
     * @param filename
     */
    private void sortByComparator(HashMap<String, Double> unsortedMap, boolean order, String filename) throws Throwable {
        List<Map.Entry<String, Double>> list = new LinkedList<>(unsortedMap.entrySet());
        Collections.sort(list, (Map.Entry<String, Double> o1, Map.Entry<String, Double> o2) -> {
            if (order) {
                return o1.getValue().compareTo(o2.getValue());
            } else {
                return o2.getValue().compareTo(o1.getValue());

            }
        });
        FileOperations fiop = new FileOperations();
        fiop.storeInFile(filename, list);
    }

    /**
     * Main method.
     *
     * @param args command line arguments
     * @throws java.lang.Throwable
     */
    public static void main(String[] args) throws Throwable {
        // TODO code application logic here
        GenerateTopicWords gTopicWords = new GenerateTopicWords();
        gTopicWords.storeTopicWordDistribution("topic_model/final.beta", "dictionary.txt");
    }

}
